#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Intima 项目完整性验证脚本。

检查项：
  1. .env.example 是否列出了所有必需的环境变量
  2. 关键文件是否存在
  3. templates/ 下模板完整性
  4. static/ 下静态资源
  5. 输出验证报告（通过 / 失败 / 警告）
"""

import os
import sys

# ---- 项目根目录 ----
PROJECT_ROOT = os.path.abspath(os.path.dirname(os.path.dirname(__file__)))
os.chdir(PROJECT_ROOT)

# ---- 必需的环境变量（.env.example 必须包含）----
REQUIRED_ENV_VARS = [
    # 核心配置
    'DEV_MODE',
    'FLASK_ENV',
    'SECRET_KEY',
    'IDCARD_KEY',
    # MongoDB Atlas
    'MONGODB_URI',
    # Upstash Redis
    'REDIS_URL',
    'CELERY_BROKER_URL',
    'CELERY_RESULT_BACKEND',
    # OAuth
    'GOOGLE_CLIENT_ID',
    'GOOGLE_CLIENT_SECRET',
    'FACEBOOK_APP_ID',
    'FACEBOOK_APP_SECRET',
    'OAUTH_REDIRECT_BASE',
    # Payment
    'CCBILL_ACCOUNT_ID',
    'CCBILL_API_KEY',
    'ECOMCHARGE_API_KEY',
    'WCPAY_API_KEY',
    'PAYMENT_SANDBOX',
    # Monitoring
    'SENTRY_DSN',
    # Deployment
    'ENV',
    'SITE_URL',
]

# ---- 关键文件检查清单 ----
CRITICAL_FILES = [
    'application/app.py',
    'configs/config.py',
    'render.yaml',
    'requirements.txt',
    'wsgi.py',
    'gunicorn.conf.py',
    '.env.example',
    '.gitignore',
    'DEPLOY.md',
    'LICENSE',
]

OPTIONAL_FILES = [
    'docker-compose.yml',
    'Dockerfile',
    'OPS.md',
    'README.md',
    'README_zh.md',
]

TEMPLATES = [
    'application/templates/base.html',
    'application/templates/index.html',
    'application/templates/static/privacy.html',
    'application/templates/static/terms.html',
    'application/templates/static/shipping.html',
    'application/templates/static/returns.html',
    'application/templates/static/about.html',
    'application/templates/errors/404.html',
    'application/templates/errors/500.html',
]

STATIC_FILES = [
    'application/static/robots.txt',
    'application/static/sitemap.xml',
    'application/static/sitemap-products.xml',
]

UTILS_FILES = [
    'application/utils/rate_limit.py',
    'application/utils/sentry.py',
    'application/utils/degradation.py',
    'application/utils/slug.py',
    'application/utils/oauth.py',
    'application/utils/logger.py',
    'application/utils/error_handler.py',
]


def color(text, code):
    """ANSI 颜色包装（Windows CMD 可能不支持但无害）。"""
    return f"\033[{code}m{text}\033[0m"


def green(t):   return color(t, '32')
def red(t):     return color(t, '31')
def yellow(t):  return color(t, '33')
def bold(t):    return color(t, '1')


def check_env_example():
    """检查 .env.example 是否包含所有必需环境变量。"""
    env_path = os.path.join(PROJECT_ROOT, '.env.example')

    if not os.path.isfile(env_path):
        return False, [red("FAIL") + " — .env.example not found"]

    with open(env_path, 'r', encoding='utf-8') as f:
        content = f.read()

    missing = []
    for var in REQUIRED_ENV_VARS:
        if var not in content:
            missing.append(var)

    if missing:
        return False, [
            red("FAIL") + f" — Missing env vars in .env.example: {', '.join(missing)}"
        ]
    return True, [green("PASS") + f" — All {len(REQUIRED_ENV_VARS)} env vars present in .env.example"]


def check_files_exist(file_list, label):
    """批量检查文件是否存在。"""
    results = []
    all_ok = True
    for fp in file_list:
        full = os.path.join(PROJECT_ROOT, fp)
        if os.path.isfile(full):
            results.append(f"  {green('OK')}  {fp}")
        else:
            results.append(f"  {red('MISS')}  {fp}")
            all_ok = False
    header = green("PASS") if all_ok else red("FAIL")
    return all_ok, [f"{header} — {label}"] + results


def check_static_resources():
    """检查 static/ 下关键文件。"""
    results = []
    all_ok = True
    for fp in STATIC_FILES:
        full = os.path.join(PROJECT_ROOT, fp)
        if os.path.isfile(full):
            results.append(f"  {green('OK')}  {fp}")
        else:
            # sitemap 相关文件可能由脚本动态生成，降级为 WARN
            if 'sitemap' in fp:
                results.append(f"  {yellow('WARN')} {fp} (generated by script)")
            else:
                results.append(f"  {red('MISS')}  {fp}")
                all_ok = False
    header = green("PASS") if all_ok else yellow("WARN")
    return all_ok, [f"{header} — Static Resources"] + results


def check_config_render_consistency():
    """检查 config.py 和 render.yaml 的关键配置项一致性。"""
    config_path = os.path.join(PROJECT_ROOT, 'configs', 'config.py')
    render_path = os.path.join(PROJECT_ROOT, 'render.yaml')

    if not os.path.isfile(config_path) or not os.path.isfile(render_path):
        return False, [red("FAIL") + " — config.py or render.yaml missing, cannot check consistency"]

    with open(config_path, 'r', encoding='utf-8') as f:
        config_content = f.read()
    with open(render_path, 'r', encoding='utf-8') as f:
        render_content = f.read()

    # 检查 render.yaml 中的 envVars key 是否在 config.py 存在
    import re
    render_keys = set(re.findall(r'- key:\s+(\w+)', render_content))

    missing = []
    for k in render_keys:
        if k.upper() not in config_content.upper() and k not in config_content:
            missing.append(k)

    if missing:
        return False, [red("FAIL") + f" — render.yaml keys missing in config.py: {missing}"]
    return True, [green("PASS") + " — config.py ↔ render.yaml env var keys consistent"]


def main():
    print(bold("\n=== Intima Project Verification ===\n"))
    print(f"Project Root: {PROJECT_ROOT}\n")

    failures = 0
    warnings = 0
    total = 0

    def run_check(name, fn):
        nonlocal failures, warnings, total
        total += 1
        ok, lines = fn()
        print(f"[{total}] {name}")
        for line in lines:
            print(line)
        if not ok and name == "Static Resources":
            warnings += 1
        elif not ok:
            failures += 1
        print()

    run_check("Environment Variables (.env.example)", check_env_example)
    run_check("Critical Files", lambda: check_files_exist(CRITICAL_FILES, "Critical Files"))
    run_check("Optional Files", lambda: check_files_exist(OPTIONAL_FILES, "Optional Files"))
    run_check("Templates", lambda: check_files_exist(TEMPLATES, "Templates"))
    run_check("Static Resources", check_static_resources)
    run_check("Utility Modules", lambda: check_files_exist(UTILS_FILES, "Utility Modules"))
    run_check("Config ↔ Render Consistency", check_config_render_consistency)

    # ---- Summary ----
    print(bold("=== SUMMARY ==="))
    passed = total - failures - warnings
    summary_parts = [
        f"{green(f'{passed} passed')}" if passed > 0 else "",
        f"{yellow(f'{warnings} warnings')}" if warnings > 0 else "",
        f"{red(f'{failures} failed')}" if failures > 0 else "",
    ]
    print(" | ".join(p for p in summary_parts if p))

    if failures == 0:
        print(green("\nAll critical checks passed!"))
        return 0
    else:
        print(red(f"\n{failures} critical check(s) failed — review above."))
        return 1


if __name__ == '__main__':
    sys.exit(main())
